matrix:
  include:
      language: scala
      scala:
        - 2.9.3
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sbt ++$TRAVIS_SCALA_VERSION test; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport coverageAggregate codacyCoverage; fi'
      language: node_js
      node_js: 
        - "8"
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      before_script:
        - npm install -g @angular/cli
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then cd client && npm install && ng build --prod && npm run test -- --no-progress --browsers=ChromeHeadlessCI --source-map=false && cd .. ; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd client && npm install && ng build --prod && npm run test -- --no-progress --browsers=ChromeHeadlessCI --source-map=false && cd .. ; fi'
      

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash <(curl -s https://codecov.io/bash); fi'
