/**
 * Delphi Instance Registry
 * The interface of the Delphi instance registry, which is responsible for connecting instances within the system as well as providing basic status information about them. For more information on Delphi, see https://github.com/delphi-hub/.
 *
 * OpenAPI spec version: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InstanceLink {
    idFrom: number;
    idTo: number;
    /**
     * Valid states for an InstanceLink
     */
    linkState: InstanceLink.LinkStateEnum;
}
export namespace InstanceLink {
    export type LinkStateEnum = 'Assigned' | 'Outdated' | 'Failed';
    export const LinkStateEnum = {
        Assigned: 'Assigned' as LinkStateEnum,
        Outdated: 'Outdated' as LinkStateEnum,
        Failed: 'Failed' as LinkStateEnum
    };
}
